name: CI
on:
  pull_request:
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Typo Check
        uses: crate-ci/typos@master
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run test
        run: nix --accept-flake-config develop -c sui-move test --warnings-are-errors --lint --coverage

      - name: Show test coverage
        run: nix --accept-flake-config develop -c sui-move coverage summary
